### ISSUE TITLE
реализовать ControllerTest

### ISSUE THREAD

**Issue by splaa** [splaa/splx_resume_heroku#1]
@seriklav [feature_controler_test](https://github.com/splaa/splx_resume_heroku/tree/feature_controler_test) - реализовать [ControllerTest](https://github.com/splaa/splx_resume_heroku/blob/feature_controler_test/tests/Unit/Http/Controllers/ControllerTest.php)

**Comment by seriklav** [comment]
не хватает Скилла для решения задачи

**Comment by seriklav** [comment]
@splaa

**Comment by splaa** [comment]
![image](https://user-images.githubusercontent.com/17740226/94339153-75208e80-0000-11eb-9e5d-fcf948c39ce7.png)
@seriklav Решание данной задачи отложим на неопределённый срок!!!
А пока так.
